import fs from "fs";
import path from "path";
import {
  buildPublicUrlInventory,
  CANONICAL_HOST,
  getSitemapChangefreq,
  getSitemapPriority,
} from "../src/lib/seo/publicUrlInventory";

const ROOT = path.resolve(__dirname, "..");
const PUBLIC_DIR = path.join(ROOT, "public");

function ensurePublicDir() {
  if (!fs.existsSync(PUBLIC_DIR)) {
    fs.mkdirSync(PUBLIC_DIR, { recursive: true });
  }
}

function renderSitemap(): string {
  const inventory = buildPublicUrlInventory();
  const lastmod = new Date().toISOString().slice(0, 10);

  const urls = inventory.allUrls
    .map((url) => {
      const pathname = url === CANONICAL_HOST ? "/" : url.replace(CANONICAL_HOST, "");
      return `  <url>
    <loc>${url}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${getSitemapChangefreq(pathname)}</changefreq>
    <priority>${getSitemapPriority(pathname).toFixed(2)}</priority>
  </url>`;
    })
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;
}

function renderRobots(): string {
  return `# Generated by scripts/generate-seo.ts — do not edit by hand
User-agent: *
Allow: /

Disallow: /thank-you
Disallow: /privacy
Disallow: /terms
Disallow: /contact

Sitemap: ${CANONICAL_HOST}/sitemap.xml
`;
}

function main() {
  ensurePublicDir();
  const inventory = buildPublicUrlInventory();

  fs.writeFileSync(path.join(PUBLIC_DIR, "sitemap.xml"), renderSitemap(), "utf8");
  fs.writeFileSync(path.join(PUBLIC_DIR, "robots.txt"), renderRobots(), "utf8");

  console.log(`Generated public/sitemap.xml (${inventory.allUrls.length} URLs)`);
  console.log("Generated public/robots.txt");
}

main();
